general.import = ["./catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "None"
blur = true
option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 17
